<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MPTNGYSzakmaianyag extends \Entities\MPTNGYSzakmaianyag implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'id', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'created', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'lastmod', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tulajdonos', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tipus', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas5', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'cim', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tartalom', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo5', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralatkesz', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kezdodatum', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kezdoido', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'konferencianszerepelhet'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'id', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'created', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'lastmod', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tulajdonos', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'szerzo4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tipus', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'eloadas5', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'cim', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'tartalom', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo4', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kulcsszo5', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralatkesz', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo1', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo2', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'biralo3', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kezdodatum', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'kezdoido', '' . "\0" . 'Entities\\MPTNGYSzakmaianyag' . "\0" . 'konferencianszerepelhet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MPTNGYSzakmaianyag $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmod', []);

        return parent::getLastmod();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmodStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmodStr', []);

        return parent::getLastmodStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedStr', []);

        return parent::getCreatedStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajdonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajdonos', []);

        return parent::getTulajdonos();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajdonosId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajdonosId', []);

        return parent::getTulajdonosId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTulajdonos($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTulajdonos', [$val]);

        return parent::setTulajdonos($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTulajdonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTulajdonos', []);

        return parent::removeTulajdonos();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo1', []);

        return parent::getSzerzo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo1Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo1Id', []);

        return parent::getSzerzo1Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo1Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo1Nev', []);

        return parent::getSzerzo1Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzerzo1($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzerzo1', [$val]);

        return parent::setSzerzo1($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSzerzo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSzerzo1', []);

        return parent::removeSzerzo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo2', []);

        return parent::getSzerzo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo2Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo2Id', []);

        return parent::getSzerzo2Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo2Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo2Nev', []);

        return parent::getSzerzo2Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzerzo2($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzerzo2', [$val]);

        return parent::setSzerzo2($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSzerzo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSzerzo2', []);

        return parent::removeSzerzo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo3', []);

        return parent::getSzerzo3();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo3Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo3Id', []);

        return parent::getSzerzo3Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo3Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo3Nev', []);

        return parent::getSzerzo3Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzerzo3($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzerzo3', [$val]);

        return parent::setSzerzo3($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSzerzo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSzerzo3', []);

        return parent::removeSzerzo3();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo4', []);

        return parent::getSzerzo4();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo4Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo4Id', []);

        return parent::getSzerzo4Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzo4Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzo4Nev', []);

        return parent::getSzerzo4Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzerzo4($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzerzo4', [$val]);

        return parent::setSzerzo4($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSzerzo4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSzerzo4', []);

        return parent::removeSzerzo4();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipus', []);

        return parent::getTipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipusId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipusId', []);

        return parent::getTipusId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipus($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipus', [$val]);

        return parent::setTipus($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTipus', []);

        return parent::removeTipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas1', []);

        return parent::getEloadas1();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas1Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas1Id', []);

        return parent::getEloadas1Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas1Cim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas1Cim', []);

        return parent::getEloadas1Cim();
    }

    /**
     * {@inheritDoc}
     */
    public function setEloadas1($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEloadas1', [$val]);

        return parent::setEloadas1($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEloadas1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEloadas1', []);

        return parent::removeEloadas1();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas2', []);

        return parent::getEloadas2();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas2Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas2Id', []);

        return parent::getEloadas2Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas2Cim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas2Cim', []);

        return parent::getEloadas2Cim();
    }

    /**
     * {@inheritDoc}
     */
    public function setEloadas2($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEloadas2', [$val]);

        return parent::setEloadas2($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEloadas2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEloadas2', []);

        return parent::removeEloadas2();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas3', []);

        return parent::getEloadas3();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas3Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas3Id', []);

        return parent::getEloadas3Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas3Cim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas3Cim', []);

        return parent::getEloadas3Cim();
    }

    /**
     * {@inheritDoc}
     */
    public function setEloadas3($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEloadas3', [$val]);

        return parent::setEloadas3($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEloadas3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEloadas3', []);

        return parent::removeEloadas3();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas4', []);

        return parent::getEloadas4();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas4Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas4Id', []);

        return parent::getEloadas4Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas4Cim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas4Cim', []);

        return parent::getEloadas4Cim();
    }

    /**
     * {@inheritDoc}
     */
    public function setEloadas4($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEloadas4', [$val]);

        return parent::setEloadas4($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEloadas4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEloadas4', []);

        return parent::removeEloadas4();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas5', []);

        return parent::getEloadas5();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas5Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas5Id', []);

        return parent::getEloadas5Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getEloadas5Cim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEloadas5Cim', []);

        return parent::getEloadas5Cim();
    }

    /**
     * {@inheritDoc}
     */
    public function setEloadas5($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEloadas5', [$val]);

        return parent::setEloadas5($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEloadas5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEloadas5', []);

        return parent::removeEloadas5();
    }

    /**
     * {@inheritDoc}
     */
    public function getCim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCim', []);

        return parent::getCim();
    }

    /**
     * {@inheritDoc}
     */
    public function setCim($cim): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCim', [$cim]);

        parent::setCim($cim);
    }

    /**
     * {@inheritDoc}
     */
    public function getTartalom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTartalom', []);

        return parent::getTartalom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTartalom($tartalom): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTartalom', [$tartalom]);

        parent::setTartalom($tartalom);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo1', []);

        return parent::getBiralo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo1Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo1Id', []);

        return parent::getBiralo1Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo1Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo1Nev', []);

        return parent::getBiralo1Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiralo1($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiralo1', [$val]);

        return parent::setBiralo1($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBiralo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBiralo1', []);

        return parent::removeBiralo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo2', []);

        return parent::getBiralo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo2Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo2Id', []);

        return parent::getBiralo2Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo2Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo2Nev', []);

        return parent::getBiralo2Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiralo2($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiralo2', [$val]);

        return parent::setBiralo2($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBiralo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBiralo2', []);

        return parent::removeBiralo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo3', []);

        return parent::getBiralo3();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo3Id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo3Id', []);

        return parent::getBiralo3Id();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiralo3Nev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiralo3Nev', []);

        return parent::getBiralo3Nev();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiralo3($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiralo3', [$val]);

        return parent::setBiralo3($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBiralo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBiralo3', []);

        return parent::removeBiralo3();
    }

    /**
     * {@inheritDoc}
     */
    public function getKulcsszo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKulcsszo1', []);

        return parent::getKulcsszo1();
    }

    /**
     * {@inheritDoc}
     */
    public function setKulcsszo1($kulcsszo1): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKulcsszo1', [$kulcsszo1]);

        parent::setKulcsszo1($kulcsszo1);
    }

    /**
     * {@inheritDoc}
     */
    public function getKulcsszo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKulcsszo2', []);

        return parent::getKulcsszo2();
    }

    /**
     * {@inheritDoc}
     */
    public function setKulcsszo2($kulcsszo2): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKulcsszo2', [$kulcsszo2]);

        parent::setKulcsszo2($kulcsszo2);
    }

    /**
     * {@inheritDoc}
     */
    public function getKulcsszo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKulcsszo3', []);

        return parent::getKulcsszo3();
    }

    /**
     * {@inheritDoc}
     */
    public function setKulcsszo3($kulcsszo3): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKulcsszo3', [$kulcsszo3]);

        parent::setKulcsszo3($kulcsszo3);
    }

    /**
     * {@inheritDoc}
     */
    public function getKulcsszo4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKulcsszo4', []);

        return parent::getKulcsszo4();
    }

    /**
     * {@inheritDoc}
     */
    public function setKulcsszo4($kulcsszo4): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKulcsszo4', [$kulcsszo4]);

        parent::setKulcsszo4($kulcsszo4);
    }

    /**
     * {@inheritDoc}
     */
    public function getKulcsszo5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKulcsszo5', []);

        return parent::getKulcsszo5();
    }

    /**
     * {@inheritDoc}
     */
    public function setKulcsszo5($kulcsszo5): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKulcsszo5', [$kulcsszo5]);

        parent::setKulcsszo5($kulcsszo5);
    }

    /**
     * {@inheritDoc}
     */
    public function isBiralatkesz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBiralatkesz', []);

        return parent::isBiralatkesz();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiralatkesz($biralatkesz): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiralatkesz', [$biralatkesz]);

        parent::setBiralatkesz($biralatkesz);
    }

    /**
     * {@inheritDoc}
     */
    public function getKezdodatum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKezdodatum', []);

        return parent::getKezdodatum();
    }

    /**
     * {@inheritDoc}
     */
    public function getKezdodatumStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKezdodatumStr', []);

        return parent::getKezdodatumStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setKezdodatum($kezdodatum): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKezdodatum', [$kezdodatum]);

        parent::setKezdodatum($kezdodatum);
    }

    /**
     * {@inheritDoc}
     */
    public function getKezdoido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKezdoido', []);

        return parent::getKezdoido();
    }

    /**
     * {@inheritDoc}
     */
    public function setKezdoido($kezdoido): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKezdoido', [$kezdoido]);

        parent::setKezdoido($kezdoido);
    }

    /**
     * {@inheritDoc}
     */
    public function isKonferencianszerepelhet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isKonferencianszerepelhet', []);

        return parent::isKonferencianszerepelhet();
    }

    /**
     * {@inheritDoc}
     */
    public function setKonferencianszerepelhet($konferencianszerepelhet): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKonferencianszerepelhet', [$konferencianszerepelhet]);

        parent::setKonferencianszerepelhet($konferencianszerepelhet);
    }

}
