<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Blokk extends \Entities\Blokk implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Blokk' . "\0" . 'id', '' . "\0" . 'Entities\\Blokk' . "\0" . 'nev', '' . "\0" . 'Entities\\Blokk' . "\0" . 'tipus', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cssclass', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cssstyle', '' . "\0" . 'Entities\\Blokk' . "\0" . 'sorrend', '' . "\0" . 'Entities\\Blokk' . "\0" . 'lathato', '' . "\0" . 'Entities\\Blokk' . "\0" . 'hatterkepurl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'videourl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cim', '' . "\0" . 'Entities\\Blokk' . "\0" . 'leiras', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gombfelirat', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gomburl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'szovegigazitas', '' . "\0" . 'Entities\\Blokk' . "\0" . 'blokkmagassag', '' . "\0" . 'Entities\\Blokk' . "\0" . 'hatterkepurl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'videourl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cim2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'leiras2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gombfelirat2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gomburl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'szovegigazitas2'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Blokk' . "\0" . 'id', '' . "\0" . 'Entities\\Blokk' . "\0" . 'nev', '' . "\0" . 'Entities\\Blokk' . "\0" . 'tipus', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cssclass', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cssstyle', '' . "\0" . 'Entities\\Blokk' . "\0" . 'sorrend', '' . "\0" . 'Entities\\Blokk' . "\0" . 'lathato', '' . "\0" . 'Entities\\Blokk' . "\0" . 'hatterkepurl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'videourl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cim', '' . "\0" . 'Entities\\Blokk' . "\0" . 'leiras', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gombfelirat', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gomburl', '' . "\0" . 'Entities\\Blokk' . "\0" . 'szovegigazitas', '' . "\0" . 'Entities\\Blokk' . "\0" . 'blokkmagassag', '' . "\0" . 'Entities\\Blokk' . "\0" . 'hatterkepurl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'videourl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'cim2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'leiras2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gombfelirat2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'gomburl2', '' . "\0" . 'Entities\\Blokk' . "\0" . 'szovegigazitas2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Blokk $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNev', []);

        return parent::getNev();
    }

    /**
     * {@inheritDoc}
     */
    public function setNev($nev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNev', [$nev]);

        return parent::setNev($nev);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipus', []);

        return parent::getTipus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipus($tipus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipus', [$tipus]);

        return parent::setTipus($tipus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssclass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssclass', []);

        return parent::getCssclass();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssclass($cssclass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssclass', [$cssclass]);

        return parent::setCssclass($cssclass);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssstyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssstyle', []);

        return parent::getCssstyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssstyle($cssstyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssstyle', [$cssstyle]);

        return parent::setCssstyle($cssstyle);
    }

    /**
     * {@inheritDoc}
     */
    public function isLathato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLathato', []);

        return parent::isLathato();
    }

    /**
     * {@inheritDoc}
     */
    public function setLathato($lathato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLathato', [$lathato]);

        return parent::setLathato($lathato);
    }

    /**
     * {@inheritDoc}
     */
    public function getSorrend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSorrend', []);

        return parent::getSorrend();
    }

    /**
     * {@inheritDoc}
     */
    public function setSorrend($sorrend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSorrend', [$sorrend]);

        return parent::setSorrend($sorrend);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl', [$pre]);

        return parent::getHatterkepurl($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurlMini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurlMini', [$pre]);

        return parent::getHatterkepurlMini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl400', [$pre]);

        return parent::getHatterkepurl400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2000', [$pre]);

        return parent::getHatterkepurl2000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurlSmall($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurlSmall', [$pre]);

        return parent::getHatterkepurlSmall($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurlMedium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurlMedium', [$pre]);

        return parent::getHatterkepurlMedium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurlLarge($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurlLarge', [$pre]);

        return parent::getHatterkepurlLarge($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setHatterkepurl($hatterkepurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHatterkepurl', [$hatterkepurl]);

        return parent::setHatterkepurl($hatterkepurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideourl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideourl', []);

        return parent::getVideourl();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideourl($videourl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideourl', [$videourl]);

        return parent::setVideourl($videourl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCim', []);

        return parent::getCim();
    }

    /**
     * {@inheritDoc}
     */
    public function setCim($cim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCim', [$cim]);

        return parent::setCim($cim);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras', []);

        return parent::getLeiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras', [$leiras]);

        return parent::setLeiras($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getGombfelirat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGombfelirat', []);

        return parent::getGombfelirat();
    }

    /**
     * {@inheritDoc}
     */
    public function setGombfelirat($gombfelirat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGombfelirat', [$gombfelirat]);

        return parent::setGombfelirat($gombfelirat);
    }

    /**
     * {@inheritDoc}
     */
    public function getGomburl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGomburl', []);

        return parent::getGomburl();
    }

    /**
     * {@inheritDoc}
     */
    public function setGomburl($gomburl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGomburl', [$gomburl]);

        return parent::setGomburl($gomburl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSzovegigazitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzovegigazitas', []);

        return parent::getSzovegigazitas();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzovegigazitas($szovegigazitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzovegigazitas', [$szovegigazitas]);

        return parent::setSzovegigazitas($szovegigazitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlokkmagassag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlokkmagassag', []);

        return parent::getBlokkmagassag();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlokkmagassag($blokkmagassag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlokkmagassag', [$blokkmagassag]);

        return parent::setBlokkmagassag($blokkmagassag);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2', [$pre]);

        return parent::getHatterkepurl2($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2Mini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2Mini', [$pre]);

        return parent::getHatterkepurl2Mini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2400', [$pre]);

        return parent::getHatterkepurl2400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl22000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl22000', [$pre]);

        return parent::getHatterkepurl22000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2Small($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2Small', [$pre]);

        return parent::getHatterkepurl2Small($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2Medium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2Medium', [$pre]);

        return parent::getHatterkepurl2Medium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHatterkepurl2Large($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHatterkepurl2Large', [$pre]);

        return parent::getHatterkepurl2Large($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setHatterkepurl2($hatterkepurl2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHatterkepurl2', [$hatterkepurl2]);

        return parent::setHatterkepurl2($hatterkepurl2);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideourl2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideourl2', []);

        return parent::getVideourl2();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideourl2($videourl2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideourl2', [$videourl2]);

        return parent::setVideourl2($videourl2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCim2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCim2', []);

        return parent::getCim2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCim2($cim2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCim2', [$cim2]);

        return parent::setCim2($cim2);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras2', []);

        return parent::getLeiras2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras2($leiras2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras2', [$leiras2]);

        return parent::setLeiras2($leiras2);
    }

    /**
     * {@inheritDoc}
     */
    public function getGombfelirat2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGombfelirat2', []);

        return parent::getGombfelirat2();
    }

    /**
     * {@inheritDoc}
     */
    public function setGombfelirat2($gombfelirat2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGombfelirat2', [$gombfelirat2]);

        return parent::setGombfelirat2($gombfelirat2);
    }

    /**
     * {@inheritDoc}
     */
    public function getGomburl2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGomburl2', []);

        return parent::getGomburl2();
    }

    /**
     * {@inheritDoc}
     */
    public function setGomburl2($gomburl2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGomburl2', [$gomburl2]);

        return parent::setGomburl2($gomburl2);
    }

    /**
     * {@inheritDoc}
     */
    public function getSzovegigazitas2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzovegigazitas2', []);

        return parent::getSzovegigazitas2();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzovegigazitas2($szovegigazitas2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzovegigazitas2', [$szovegigazitas2]);

        return parent::setSzovegigazitas2($szovegigazitas2);
    }

}
