<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TermekMenu extends \Entities\TermekMenu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'gtnev', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'id', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'created', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'lastmod', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'children', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'parent', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'termekmenufa', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'nev', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'nev_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'sorrend', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'slug', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'rovidleiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'rovidleiras_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras2', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras2_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras3', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras3_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'oldalcim', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'seodescription', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'kepurl', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'kepleiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'inaktiv', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'idegenkod', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'arukeresoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'gtnev', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'id', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'created', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'lastmod', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'children', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'parent', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'termekmenufa', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'nev', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'nev_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'sorrend', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'slug', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'rovidleiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'rovidleiras_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras2', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras2_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras3', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'leiras3_l1', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'oldalcim', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'seodescription', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'kepurl', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'kepleiras', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'inaktiv', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'idegenkod', '' . "\0" . 'Entities\\TermekMenu' . "\0" . 'arukeresoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TermekMenu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toA2a()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toA2a', []);

        return parent::toA2a();
    }

    /**
     * {@inheritDoc}
     */
    public function toLista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toLista', []);

        return parent::toLista();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\Entities\TermekMenu $child)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$child]);

        return parent::addChild($child);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChild(\Entities\TermekMenu $child)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChild', [$child]);

        return parent::removeChild($child);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentId', []);

        return parent::getParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentNev', []);

        return parent::getParentNev();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentNevLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentNevLocale', []);

        return parent::getParentNevLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Entities\TermekMenu $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParent', []);

        return parent::removeParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getTermekmenufa(): ?\Entities\TermekMenuFa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermekmenufa', []);

        return parent::getTermekmenufa();
    }

    /**
     * {@inheritDoc}
     */
    public function getTermekmenufaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermekmenufaId', []);

        return parent::getTermekmenufaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermekmenufa(\Entities\TermekMenuFa $termekmenufa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermekmenufa', [$termekmenufa]);

        return parent::setTermekmenufa($termekmenufa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeljesNev($elval = '|', $selfname = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeljesNev', [$elval, $selfname]);

        return parent::getTeljesNev($elval, $selfname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNev', []);

        return parent::getNev();
    }

    /**
     * {@inheritDoc}
     */
    public function setNev($nev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNev', [$nev]);

        return parent::setNev($nev);
    }

    /**
     * {@inheritDoc}
     */
    public function getNevL1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNevL1', []);

        return parent::getNevL1();
    }

    /**
     * {@inheritDoc}
     */
    public function setNevL1($nev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNevL1', [$nev]);

        return parent::setNevL1($nev);
    }

    /**
     * {@inheritDoc}
     */
    public function getSorrend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSorrend', []);

        return parent::getSorrend();
    }

    /**
     * {@inheritDoc}
     */
    public function setSorrend($sorrend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSorrend', [$sorrend]);

        return parent::setSorrend($sorrend);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras', []);

        return parent::getLeiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras', [$leiras]);

        return parent::setLeiras($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeirasL1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeirasL1', []);

        return parent::getLeirasL1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeirasL1($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeirasL1', [$leiras]);

        return parent::setLeirasL1($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras2', []);

        return parent::getLeiras2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras2($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras2', [$leiras]);

        return parent::setLeiras2($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras2L1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras2L1', []);

        return parent::getLeiras2L1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras2L1($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras2L1', [$leiras]);

        return parent::setLeiras2L1($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras3', []);

        return parent::getLeiras3();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras3($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras3', [$leiras]);

        return parent::setLeiras3($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras3L1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras3L1', []);

        return parent::getLeiras3L1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras3L1($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras3L1', [$leiras]);

        return parent::setLeiras3L1($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldalcim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldalcim', []);

        return parent::getOldalcim();
    }

    /**
     * {@inheritDoc}
     */
    public function getShowOldalcim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowOldalcim', []);

        return parent::getShowOldalcim();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldalcim($oldalcim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldalcim', [$oldalcim]);

        return parent::setOldalcim($oldalcim);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeodescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeodescription', []);

        return parent::getSeodescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getShowSeodescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowSeodescription', []);

        return parent::getShowSeodescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeodescription($seodescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeodescription', [$seodescription]);

        return parent::setSeodescription($seodescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl', [$pre]);

        return parent::getKepurl($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlMini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlMini', [$pre]);

        return parent::getKepurlMini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlSmall($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlSmall', [$pre]);

        return parent::getKepurlSmall($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlMedium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlMedium', [$pre]);

        return parent::getKepurlMedium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlLarge($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlLarge', [$pre]);

        return parent::getKepurlLarge($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setKepurl($kepurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepurl', [$kepurl]);

        return parent::setKepurl($kepurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepleiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepleiras', []);

        return parent::getKepleiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setKepleiras($kepleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepleiras', [$kepleiras]);

        return parent::setKepleiras($kepleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeletable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeletable', []);

        return parent::isDeletable();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmod', []);

        return parent::getLastmod();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getRovidleiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRovidleiras', []);

        return parent::getRovidleiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setRovidleiras($rovidleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRovidleiras', [$rovidleiras]);

        return parent::setRovidleiras($rovidleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getRovidleirasL1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRovidleirasL1', []);

        return parent::getRovidleirasL1();
    }

    /**
     * {@inheritDoc}
     */
    public function setRovidleirasL1($rovidleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRovidleirasL1', [$rovidleiras]);

        return parent::setRovidleirasL1($rovidleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getInaktiv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInaktiv', []);

        return parent::getInaktiv();
    }

    /**
     * {@inheritDoc}
     */
    public function setInaktiv($i)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInaktiv', [$i]);

        return parent::setInaktiv($i);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdegenkod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdegenkod', []);

        return parent::getIdegenkod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdegenkod($idegenkod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdegenkod', [$idegenkod]);

        return parent::setIdegenkod($idegenkod);
    }

    /**
     * {@inheritDoc}
     */
    public function getArukeresoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArukeresoid', []);

        return parent::getArukeresoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setArukeresoid($arukeresoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArukeresoid', [$arukeresoid]);

        return parent::setArukeresoid($arukeresoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath($parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', [$parent]);

        return parent::getPath($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldValue($fieldName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldValue', [$fieldName]);

        return parent::getFieldValue($fieldName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalizedFieldValue($fieldname, $locale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalizedFieldValue', [$fieldname, $locale]);

        return parent::getLocalizedFieldValue($fieldname, $locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalizedFieldValueOrDefault($fieldname, $locale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalizedFieldValueOrDefault', [$fieldname, $locale]);

        return parent::getLocalizedFieldValueOrDefault($fieldname, $locale);
    }

}
