<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bankbizonylatfej extends \Entities\Bankbizonylatfej implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'id', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'created', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'lastmod', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bizonylattipus', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'irany', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'rontott', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'erbizonylatszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'megjegyzes', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'kelt', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'netto', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'afa', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'brutto', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'valutanem', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'valutanemnev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bankszamla', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajbanknev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajbankszamlaszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajswift', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajiban', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partner', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnernev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnervezeteknev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerkeresztnev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partneradoszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnereuadoszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerirszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnervaros', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerutca', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bizonylattetelek', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'folyoszamlak');
        }

        return array('__isInitialized__', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'id', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'created', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'lastmod', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bizonylattipus', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'irany', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'rontott', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'erbizonylatszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'megjegyzes', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'kelt', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'netto', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'afa', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'brutto', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'valutanem', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'valutanemnev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bankszamla', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajbanknev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajbankszamlaszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajswift', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'tulajiban', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partner', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnernev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnervezeteknev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerkeresztnev', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partneradoszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnereuadoszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerirszam', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnervaros', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'partnerutca', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'bizonylattetelek', '' . "\0" . 'Entities\\Bankbizonylatfej' . "\0" . 'folyoszamlak');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bankbizonylatfej $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function generateFolyoszamla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateFolyoszamla', array());

        return parent::generateFolyoszamla();
    }

    /**
     * {@inheritDoc}
     */
    public function calcOsszesen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calcOsszesen', array());

        return parent::calcOsszesen();
    }

    /**
     * {@inheritDoc}
     */
    public function generateId($from = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateId', array($from));

        return parent::generateId($from);
    }

    /**
     * {@inheritDoc}
     */
    public function doStuffOnPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doStuffOnPrePersist', array());

        return parent::doStuffOnPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getBizonylattetelek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBizonylattetelek', array());

        return parent::getBizonylattetelek();
    }

    /**
     * {@inheritDoc}
     */
    public function addBizonylattetel(\Entities\Bankbizonylattetel $val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBizonylattetel', array($val));

        return parent::addBizonylattetel($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBizonylattetel(\Entities\Bizonylattetel $val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBizonylattetel', array($val));

        return parent::removeBizonylattetel($val);
    }

    /**
     * {@inheritDoc}
     */
    public function clearBizonylattetelek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearBizonylattetelek', array());

        return parent::clearBizonylattetelek();
    }

    /**
     * {@inheritDoc}
     */
    public function getFolyoszamlak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolyoszamlak', array());

        return parent::getFolyoszamlak();
    }

    /**
     * {@inheritDoc}
     */
    public function addFolyoszamla(\Entities\Folyoszamla $val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFolyoszamla', array($val));

        return parent::addFolyoszamla($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFolyoszamla(\Entities\Folyoszamla $val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFolyoszamla', array($val));

        return parent::removeFolyoszamla($val);
    }

    /**
     * {@inheritDoc}
     */
    public function clearFolyoszamlak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearFolyoszamlak', array());

        return parent::clearFolyoszamlak();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrany', array());

        return parent::getIrany();
    }

    /**
     * {@inheritDoc}
     */
    public function setIrany($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIrany', array($val));

        return parent::setIrany($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getBizonylattipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBizonylattipus', array());

        return parent::getBizonylattipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getBizonylattipusId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBizonylattipusId', array());

        return parent::getBizonylattipusId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBizonylattipus($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBizonylattipus', array($val));

        return parent::setBizonylattipus($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBizonylattipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBizonylattipus', array());

        return parent::removeBizonylattipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getKelt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKelt', array());

        return parent::getKelt();
    }

    /**
     * {@inheritDoc}
     */
    public function getKeltStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeltStr', array());

        return parent::getKeltStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setKelt($adat = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKelt', array($adat));

        return parent::setKelt($adat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetto', array());

        return parent::getNetto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetto($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetto', array($val));

        return parent::setNetto($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getAfa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAfa', array());

        return parent::getAfa();
    }

    /**
     * {@inheritDoc}
     */
    public function setAfa($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAfa', array($val));

        return parent::setAfa($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrutto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrutto', array());

        return parent::getBrutto();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrutto($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrutto', array($val));

        return parent::setBrutto($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getValutanem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValutanem', array());

        return parent::getValutanem();
    }

    /**
     * {@inheritDoc}
     */
    public function getValutanemnev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValutanemnev', array());

        return parent::getValutanemnev();
    }

    /**
     * {@inheritDoc}
     */
    public function getValutanemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValutanemId', array());

        return parent::getValutanemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValutanem($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValutanem', array($val));

        return parent::setValutanem($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeValutanem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeValutanem', array());

        return parent::removeValutanem();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', array());

        return parent::getPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerId', array());

        return parent::getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', array($val));

        return parent::setPartner($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removePartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePartner', array());

        return parent::removePartner();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnernev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnernev', array());

        return parent::getPartnernev();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnernev($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnernev', array($val));

        return parent::setPartnernev($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnervezeteknev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnervezeteknev', array());

        return parent::getPartnervezeteknev();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnervezeteknev($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnervezeteknev', array($val));

        return parent::setPartnervezeteknev($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerkeresztnev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerkeresztnev', array());

        return parent::getPartnerkeresztnev();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerkeresztnev($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerkeresztnev', array($val));

        return parent::setPartnerkeresztnev($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartneradoszam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartneradoszam', array());

        return parent::getPartneradoszam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartneradoszam($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartneradoszam', array($val));

        return parent::setPartneradoszam($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnereuadoszam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnereuadoszam', array());

        return parent::getPartnereuadoszam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnereuadoszam($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnereuadoszam', array($val));

        return parent::setPartnereuadoszam($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerirszam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerirszam', array());

        return parent::getPartnerirszam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerirszam($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerirszam', array($val));

        return parent::setPartnerirszam($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerutca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerutca', array());

        return parent::getPartnerutca();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerutca($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerutca', array($val));

        return parent::setPartnerutca($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnervaros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnervaros', array());

        return parent::getPartnervaros();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnervaros($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnervaros', array($val));

        return parent::setPartnervaros($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankszamla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankszamla', array());

        return parent::getBankszamla();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajbankszamlaszam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajbankszamlaszam', array());

        return parent::getTulajbankszamlaszam();
    }

    /**
     * {@inheritDoc}
     */
    public function getBankszamlaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankszamlaId', array());

        return parent::getBankszamlaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankszamla($val = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankszamla', array($val));

        return parent::setBankszamla($val);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBankszamla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBankszamla', array());

        return parent::removeBankszamla();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajswift()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajswift', array());

        return parent::getTulajswift();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajbanknev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajbanknev', array());

        return parent::getTulajbanknev();
    }

    /**
     * {@inheritDoc}
     */
    public function getTulajiban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTulajiban', array());

        return parent::getTulajiban();
    }

    /**
     * {@inheritDoc}
     */
    public function getErbizonylatszam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErbizonylatszam', array());

        return parent::getErbizonylatszam();
    }

    /**
     * {@inheritDoc}
     */
    public function setErbizonylatszam($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setErbizonylatszam', array($val));

        return parent::setErbizonylatszam($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getMegjegyzes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMegjegyzes', array());

        return parent::getMegjegyzes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMegjegyzes($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMegjegyzes', array($val));

        return parent::setMegjegyzes($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmod', array());

        return parent::getLastmod();
    }

    /**
     * {@inheritDoc}
     */
    public function clearLastmod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearLastmod', array());

        return parent::clearLastmod();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function clearCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearCreated', array());

        return parent::clearCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getRontott()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRontott', array());

        return parent::getRontott();
    }

    /**
     * {@inheritDoc}
     */
    public function setRontott($adat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRontott', array($adat));

        return parent::setRontott($adat);
    }

}
