<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eppjelszo extends \Entities\Eppjelszo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'id', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'created', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'lastmod', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'createdby', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'updatedby', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'azonosito', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'oldalid', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'jelszohash', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'jelszokereso', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'lejarat', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'megjegyzes', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'visszavonvaon', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'visszavonvaby'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'id', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'created', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'lastmod', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'createdby', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'updatedby', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'azonosito', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'oldalid', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'jelszohash', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'jelszokereso', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'lejarat', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'megjegyzes', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'visszavonvaon', '' . "\0" . 'Entities\\Eppjelszo' . "\0" . 'visszavonvaby'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eppjelszo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function generateJelszo(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateJelszo', []);

        return parent::generateJelszo();
    }

    /**
     * {@inheritDoc}
     */
    public function checkJelszo(string $jelszo): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkJelszo', [$jelszo]);

        return parent::checkJelszo($jelszo);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisszavonva(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisszavonva', []);

        return parent::isVisszavonva();
    }

    /**
     * {@inheritDoc}
     */
    public function isLejart(?\DateTimeInterface $most = NULL): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLejart', [$most]);

        return parent::isLejart($most);
    }

    /**
     * {@inheritDoc}
     */
    public function isAktiv(?\DateTimeInterface $most = NULL): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAktiv', [$most]);

        return parent::isAktiv($most);
    }

    /**
     * {@inheritDoc}
     */
    public function revoke(?\Entities\Dolgozo $dolgozo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'revoke', [$dolgozo]);

        return parent::revoke($dolgozo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedStr', []);

        return parent::getCreatedStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastmod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastmod', []);

        return parent::getLastmod();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedby', []);

        return parent::getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedbyNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedbyNev', []);

        return parent::getCreatedbyNev();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedby', []);

        return parent::getUpdatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function getAzonosito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAzonosito', []);

        return parent::getAzonosito();
    }

    /**
     * {@inheritDoc}
     */
    public function getOldalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldalid', []);

        return parent::getOldalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldalid($oldalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldalid', [$oldalid]);

        return parent::setOldalid($oldalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getLejarat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLejarat', []);

        return parent::getLejarat();
    }

    /**
     * {@inheritDoc}
     */
    public function getLejaratStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLejaratStr', []);

        return parent::getLejaratStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getLejaratTimestamp(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLejaratTimestamp', []);

        return parent::getLejaratTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLejarat($adat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLejarat', [$adat]);

        return parent::setLejarat($adat);
    }

    /**
     * {@inheritDoc}
     */
    public function getMegjegyzes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMegjegyzes', []);

        return parent::getMegjegyzes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMegjegyzes($megjegyzes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMegjegyzes', [$megjegyzes]);

        return parent::setMegjegyzes($megjegyzes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisszavonvaon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisszavonvaon', []);

        return parent::getVisszavonvaon();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisszavonvaonStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisszavonvaonStr', []);

        return parent::getVisszavonvaonStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisszavonvaby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisszavonvaby', []);

        return parent::getVisszavonvaby();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisszavonvabyNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisszavonvabyNev', []);

        return parent::getVisszavonvabyNev();
    }

}
