<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cronlog extends \Entities\Cronlog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'id', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'feladat', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'allapot', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'kezdet', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'veg', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'idotartam', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'uzenet', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'host', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'pid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'id', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'feladat', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'allapot', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'kezdet', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'veg', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'idotartam', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'uzenet', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'host', '' . "\0" . 'Entities\\Cronlog' . "\0" . 'pid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cronlog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeladat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeladat', []);

        return parent::getFeladat();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeladat($feladat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeladat', [$feladat]);

        return parent::setFeladat($feladat);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllapot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllapot', []);

        return parent::getAllapot();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllapot($allapot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllapot', [$allapot]);

        return parent::setAllapot($allapot);
    }

    /**
     * {@inheritDoc}
     */
    public function getKezdet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKezdet', []);

        return parent::getKezdet();
    }

    /**
     * {@inheritDoc}
     */
    public function getKezdetStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKezdetStr', []);

        return parent::getKezdetStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setKezdet($kezdet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKezdet', [$kezdet]);

        return parent::setKezdet($kezdet);
    }

    /**
     * {@inheritDoc}
     */
    public function getVeg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVeg', []);

        return parent::getVeg();
    }

    /**
     * {@inheritDoc}
     */
    public function getVegStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVegStr', []);

        return parent::getVegStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setVeg($veg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVeg', [$veg]);

        return parent::setVeg($veg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdotartam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdotartam', []);

        return parent::getIdotartam();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdotartamStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdotartamStr', []);

        return parent::getIdotartamStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdotartam($idotartam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdotartam', [$idotartam]);

        return parent::setIdotartam($idotartam);
    }

    /**
     * {@inheritDoc}
     */
    public function getUzenet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUzenet', []);

        return parent::getUzenet();
    }

    /**
     * {@inheritDoc}
     */
    public function setUzenet($uzenet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUzenet', [$uzenet]);

        return parent::setUzenet($uzenet);
    }

    /**
     * {@inheritDoc}
     */
    public function getHost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHost', []);

        return parent::getHost();
    }

    /**
     * {@inheritDoc}
     */
    public function setHost($host)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHost', [$host]);

        return parent::setHost($host);
    }

    /**
     * {@inheritDoc}
     */
    public function getPid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPid', []);

        return parent::getPid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPid($pid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPid', [$pid]);

        return parent::setPid($pid);
    }

}
