<?php

namespace Proxies\__CG__\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Versenyzo extends \Entities\Versenyzo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'id', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'nev', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'slug', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'versenysorozat', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'rovidleiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'leiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl1', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras1', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl2', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras2', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl3', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras3', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'csapat'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'id', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'nev', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'slug', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'versenysorozat', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'rovidleiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'leiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl1', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras1', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl2', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras2', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepurl3', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'kepleiras3', '' . "\0" . 'Entities\\Versenyzo' . "\0" . 'csapat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Versenyzo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNev', []);

        return parent::getNev();
    }

    /**
     * {@inheritDoc}
     */
    public function setNev($nev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNev', [$nev]);

        return parent::setNev($nev);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenysorozat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenysorozat', []);

        return parent::getVersenysorozat();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenysorozat($versenysorozat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenysorozat', [$versenysorozat]);

        return parent::setVersenysorozat($versenysorozat);
    }

    /**
     * {@inheritDoc}
     */
    public function getRovidleiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRovidleiras', []);

        return parent::getRovidleiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setRovidleiras($rovidleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRovidleiras', [$rovidleiras]);

        return parent::setRovidleiras($rovidleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeiras', []);

        return parent::getLeiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeiras($leiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeiras', [$leiras]);

        return parent::setLeiras($leiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl', [$pre]);

        return parent::getKepurl($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlMini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlMini', [$pre]);

        return parent::getKepurlMini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlSmall($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlSmall', [$pre]);

        return parent::getKepurlSmall($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlMedium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlMedium', [$pre]);

        return parent::getKepurlMedium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurlLarge($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurlLarge', [$pre]);

        return parent::getKepurlLarge($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl400', [$pre]);

        return parent::getKepurl400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2000', [$pre]);

        return parent::getKepurl2000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setKepurl($kep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepurl', [$kep]);

        return parent::setKepurl($kep);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepleiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepleiras', []);

        return parent::getKepleiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setKepleiras($kepleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepleiras', [$kepleiras]);

        return parent::setKepleiras($kepleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1', [$pre]);

        return parent::getKepurl1($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1Mini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1Mini', [$pre]);

        return parent::getKepurl1Mini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1Small($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1Small', [$pre]);

        return parent::getKepurl1Small($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1Medium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1Medium', [$pre]);

        return parent::getKepurl1Medium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1Large($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1Large', [$pre]);

        return parent::getKepurl1Large($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl1400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl1400', [$pre]);

        return parent::getKepurl1400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl12000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl12000', [$pre]);

        return parent::getKepurl12000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setKepurl1($kep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepurl1', [$kep]);

        return parent::setKepurl1($kep);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepleiras1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepleiras1', []);

        return parent::getKepleiras1();
    }

    /**
     * {@inheritDoc}
     */
    public function setKepleiras1($kepleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepleiras1', [$kepleiras]);

        return parent::setKepleiras1($kepleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2', [$pre]);

        return parent::getKepurl2($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2Mini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2Mini', [$pre]);

        return parent::getKepurl2Mini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2Small($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2Small', [$pre]);

        return parent::getKepurl2Small($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2Medium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2Medium', [$pre]);

        return parent::getKepurl2Medium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2Large($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2Large', [$pre]);

        return parent::getKepurl2Large($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl2400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl2400', [$pre]);

        return parent::getKepurl2400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl22000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl22000', [$pre]);

        return parent::getKepurl22000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setKepurl2($kep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepurl2', [$kep]);

        return parent::setKepurl2($kep);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepleiras2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepleiras2', []);

        return parent::getKepleiras2();
    }

    /**
     * {@inheritDoc}
     */
    public function setKepleiras2($kepleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepleiras2', [$kepleiras]);

        return parent::setKepleiras2($kepleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3', [$pre]);

        return parent::getKepurl3($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3Mini($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3Mini', [$pre]);

        return parent::getKepurl3Mini($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3Small($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3Small', [$pre]);

        return parent::getKepurl3Small($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3Medium($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3Medium', [$pre]);

        return parent::getKepurl3Medium($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3Large($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3Large', [$pre]);

        return parent::getKepurl3Large($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl3400($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl3400', [$pre]);

        return parent::getKepurl3400($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepurl32000($pre = '/')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepurl32000', [$pre]);

        return parent::getKepurl32000($pre);
    }

    /**
     * {@inheritDoc}
     */
    public function setKepurl3($kep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepurl3', [$kep]);

        return parent::setKepurl3($kep);
    }

    /**
     * {@inheritDoc}
     */
    public function getKepleiras3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKepleiras3', []);

        return parent::getKepleiras3();
    }

    /**
     * {@inheritDoc}
     */
    public function setKepleiras3($kepleiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKepleiras3', [$kepleiras]);

        return parent::setKepleiras3($kepleiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getCsapat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsapat', []);

        return parent::getCsapat();
    }

    /**
     * {@inheritDoc}
     */
    public function getCsapatNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsapatNev', []);

        return parent::getCsapatNev();
    }

    /**
     * {@inheritDoc}
     */
    public function getCsapatId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsapatId', []);

        return parent::getCsapatId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCsapat($csapat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCsapat', [$csapat]);

        return parent::setCsapat($csapat);
    }

}
