<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesJelenletiivProxy extends \Entities\Jelenletiiv implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getDatum()
    {
        $this->__load();
        return parent::getDatum();
    }

    public function getDatumStr()
    {
        $this->__load();
        return parent::getDatumStr();
    }

    public function setDatum($adat)
    {
        $this->__load();
        return parent::setDatum($adat);
    }

    public function getDolgozo()
    {
        $this->__load();
        return parent::getDolgozo();
    }

    public function getDolgozoNev()
    {
        $this->__load();
        return parent::getDolgozoNev();
    }

    public function getDolgozoId()
    {
        $this->__load();
        return parent::getDolgozoId();
    }

    public function setDolgozo(\Entities\Dolgozo $adat)
    {
        $this->__load();
        return parent::setDolgozo($adat);
    }

    public function removeDolgozo()
    {
        $this->__load();
        return parent::removeDolgozo();
    }

    public function getMunkaido()
    {
        $this->__load();
        return parent::getMunkaido();
    }

    public function setMunkaido($adat)
    {
        $this->__load();
        return parent::setMunkaido($adat);
    }

    public function getJelenlettipus()
    {
        $this->__load();
        return parent::getJelenlettipus();
    }

    public function getJelenlettipusNev()
    {
        $this->__load();
        return parent::getJelenlettipusNev();
    }

    public function getJelenlettipusId()
    {
        $this->__load();
        return parent::getJelenlettipusId();
    }

    public function setJelenlettipus(\Entities\Jelenlettipus $adat)
    {
        $this->__load();
        return parent::setJelenlettipus($adat);
    }

    public function removeJelenlettipus()
    {
        $this->__load();
        return parent::removeJelenlettipus();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'datum', 'dolgozo', 'munkaido', 'jelenlettipus');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}