<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesPartnerProxy extends \Entities\Partner implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getCim()
    {
        $this->__load();
        return parent::getCim();
    }

    public function getLCim()
    {
        $this->__load();
        return parent::getLCim();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getInaktiv()
    {
        $this->__load();
        return parent::getInaktiv();
    }

    public function setInaktiv($inaktiv)
    {
        $this->__load();
        return parent::setInaktiv($inaktiv);
    }

    public function getNev()
    {
        $this->__load();
        return parent::getNev();
    }

    public function setNev($nev)
    {
        $this->__load();
        return parent::setNev($nev);
    }

    public function getVezeteknev()
    {
        $this->__load();
        return parent::getVezeteknev();
    }

    public function setVezeteknev($adat)
    {
        $this->__load();
        return parent::setVezeteknev($adat);
    }

    public function getKeresztnev()
    {
        $this->__load();
        return parent::getKeresztnev();
    }

    public function setKeresztnev($adat)
    {
        $this->__load();
        return parent::setKeresztnev($adat);
    }

    public function getAdoszam()
    {
        $this->__load();
        return parent::getAdoszam();
    }

    public function setAdoszam($adoszam)
    {
        $this->__load();
        return parent::setAdoszam($adoszam);
    }

    public function getEuadoszam()
    {
        $this->__load();
        return parent::getEuadoszam();
    }

    public function setEuadoszam($euadoszam)
    {
        $this->__load();
        return parent::setEuadoszam($euadoszam);
    }

    public function getMukengszam()
    {
        $this->__load();
        return parent::getMukengszam();
    }

    public function setMukengszam($mukengszam)
    {
        $this->__load();
        return parent::setMukengszam($mukengszam);
    }

    public function getJovengszam()
    {
        $this->__load();
        return parent::getJovengszam();
    }

    public function setJovengszam($jovengszam)
    {
        $this->__load();
        return parent::setJovengszam($jovengszam);
    }

    public function getOstermszam()
    {
        $this->__load();
        return parent::getOstermszam();
    }

    public function setOstermszam($ostermszam)
    {
        $this->__load();
        return parent::setOstermszam($ostermszam);
    }

    public function getValligszam()
    {
        $this->__load();
        return parent::getValligszam();
    }

    public function setValligszam($valligszam)
    {
        $this->__load();
        return parent::setValligszam($valligszam);
    }

    public function getFvmszam()
    {
        $this->__load();
        return parent::getFvmszam();
    }

    public function setFvmszam($fvmszam)
    {
        $this->__load();
        return parent::setFvmszam($fvmszam);
    }

    public function getCjszam()
    {
        $this->__load();
        return parent::getCjszam();
    }

    public function setCjszam($cjszam)
    {
        $this->__load();
        return parent::setCjszam($cjszam);
    }

    public function getIrszam()
    {
        $this->__load();
        return parent::getIrszam();
    }

    public function setIrszam($irszam)
    {
        $this->__load();
        return parent::setIrszam($irszam);
    }

    public function getVaros()
    {
        $this->__load();
        return parent::getVaros();
    }

    public function setVaros($varos)
    {
        $this->__load();
        return parent::setVaros($varos);
    }

    public function getUtca()
    {
        $this->__load();
        return parent::getUtca();
    }

    public function setUtca($utca)
    {
        $this->__load();
        return parent::setUtca($utca);
    }

    public function getLirszam()
    {
        $this->__load();
        return parent::getLirszam();
    }

    public function setLirszam($lirszam)
    {
        $this->__load();
        return parent::setLirszam($lirszam);
    }

    public function getLvaros()
    {
        $this->__load();
        return parent::getLvaros();
    }

    public function setLvaros($lvaros)
    {
        $this->__load();
        return parent::setLvaros($lvaros);
    }

    public function getLutca()
    {
        $this->__load();
        return parent::getLutca();
    }

    public function setLutca($lutca)
    {
        $this->__load();
        return parent::setLutca($lutca);
    }

    public function getTelefon()
    {
        $this->__load();
        return parent::getTelefon();
    }

    public function setTelefon($telefon)
    {
        $this->__load();
        return parent::setTelefon($telefon);
    }

    public function getMobil()
    {
        $this->__load();
        return parent::getMobil();
    }

    public function setMobil($mobil)
    {
        $this->__load();
        return parent::setMobil($mobil);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getHonlap()
    {
        $this->__load();
        return parent::getHonlap();
    }

    public function setHonlap($honlap)
    {
        $this->__load();
        return parent::setHonlap($honlap);
    }

    public function getMegjegyzes()
    {
        $this->__load();
        return parent::getMegjegyzes();
    }

    public function setMegjegyzes($megjegyzes)
    {
        $this->__load();
        return parent::setMegjegyzes($megjegyzes);
    }

    public function getSyncid()
    {
        $this->__load();
        return parent::getSyncid();
    }

    public function setSyncid($syncid)
    {
        $this->__load();
        return parent::setSyncid($syncid);
    }

    public function getUzletkoto()
    {
        $this->__load();
        return parent::getUzletkoto();
    }

    public function getUzletkotoNev()
    {
        $this->__load();
        return parent::getUzletkotoNev();
    }

    public function getUzletkotoId()
    {
        $this->__load();
        return parent::getUzletkotoId();
    }

    public function setUzletkoto(\Entities\Uzletkoto $uzletkoto)
    {
        $this->__load();
        return parent::setUzletkoto($uzletkoto);
    }

    public function removeUzletkoto()
    {
        $this->__load();
        return parent::removeUzletkoto();
    }

    public function addEsemeny($esemeny)
    {
        $this->__load();
        return parent::addEsemeny($esemeny);
    }

    public function getEsemenyek()
    {
        $this->__load();
        return parent::getEsemenyek();
    }

    public function removeEsemeny($esemeny)
    {
        $this->__load();
        return parent::removeEsemeny($esemeny);
    }

    public function addTeendo($teendo)
    {
        $this->__load();
        return parent::addTeendo($teendo);
    }

    public function getTeendok()
    {
        $this->__load();
        return parent::getTeendok();
    }

    public function removeTeendo($teendo)
    {
        $this->__load();
        return parent::removeTeendo($teendo);
    }

    public function getCimkek()
    {
        $this->__load();
        return parent::getCimkek();
    }

    public function getCimkeNevek()
    {
        $this->__load();
        return parent::getCimkeNevek();
    }

    public function addCimke(\Entities\Cimketorzs $cimke)
    {
        $this->__load();
        return parent::addCimke($cimke);
    }

    public function removeCimke(\Entities\Cimketorzs $cimke)
    {
        $this->__load();
        return parent::removeCimke($cimke);
    }

    public function removeAllCimke()
    {
        $this->__load();
        return parent::removeAllCimke();
    }

    public function getFizmod()
    {
        $this->__load();
        return parent::getFizmod();
    }

    public function getFizmodNev()
    {
        $this->__load();
        return parent::getFizmodNev();
    }

    public function getFizmodId()
    {
        $this->__load();
        return parent::getFizmodId();
    }

    public function setFizmod(\Entities\Fizmod $fizmod)
    {
        $this->__load();
        return parent::setFizmod($fizmod);
    }

    public function getIdegenkod()
    {
        $this->__load();
        return parent::getIdegenkod();
    }

    public function setIdegenkod($idegenkod)
    {
        $this->__load();
        return parent::setIdegenkod($idegenkod);
    }

    public function getStatszamjel()
    {
        $this->__load();
        return parent::getStatszamjel();
    }

    public function setStatszamjel($statszamjel)
    {
        $this->__load();
        return parent::setStatszamjel($statszamjel);
    }

    public function getFizhatido()
    {
        $this->__load();
        return parent::getFizhatido();
    }

    public function setFizhatido($val)
    {
        $this->__load();
        return parent::setFizhatido($val);
    }

    public function getLastmod()
    {
        $this->__load();
        return parent::getLastmod();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function getSzallnev()
    {
        $this->__load();
        return parent::getSzallnev();
    }

    public function setSzallnev($adat)
    {
        $this->__load();
        return parent::setSzallnev($adat);
    }

    public function getSzallirszam()
    {
        $this->__load();
        return parent::getSzallirszam();
    }

    public function setSzallirszam($adat)
    {
        $this->__load();
        return parent::setSzallirszam($adat);
    }

    public function getSzallvaros()
    {
        $this->__load();
        return parent::getSzallvaros();
    }

    public function setSzallvaros($adat)
    {
        $this->__load();
        return parent::setSzallvaros($adat);
    }

    public function getSzallutca()
    {
        $this->__load();
        return parent::getSzallutca();
    }

    public function setSzallutca($adat)
    {
        $this->__load();
        return parent::setSzallutca($adat);
    }

    public function getNem()
    {
        $this->__load();
        return parent::getNem();
    }

    public function setNem($adat)
    {
        $this->__load();
        return parent::setNem($adat);
    }

    public function getSzuletesiido()
    {
        $this->__load();
        return parent::getSzuletesiido();
    }

    public function getSzuletesiidoStr()
    {
        $this->__load();
        return parent::getSzuletesiidoStr();
    }

    public function setSzuletesiido($adat = '')
    {
        $this->__load();
        return parent::setSzuletesiido($adat);
    }

    public function getAkcioshirlevelkell()
    {
        $this->__load();
        return parent::getAkcioshirlevelkell();
    }

    public function setAkcioshirlevelkell($adat)
    {
        $this->__load();
        return parent::setAkcioshirlevelkell($adat);
    }

    public function getUjdonsaghirlevelkell()
    {
        $this->__load();
        return parent::getUjdonsaghirlevelkell();
    }

    public function setUjdonsaghirlevelkell($adat)
    {
        $this->__load();
        return parent::setUjdonsaghirlevelkell($adat);
    }

    public function getSessionid()
    {
        $this->__load();
        return parent::getSessionid();
    }

    public function setSessionid($adat)
    {
        $this->__load();
        return parent::setSessionid($adat);
    }

    public function getJelszo()
    {
        $this->__load();
        return parent::getJelszo();
    }

    public function setMkwJelszo($adat)
    {
        $this->__load();
        return parent::setMkwJelszo($adat);
    }

    public function setJelszo($adat)
    {
        $this->__load();
        return parent::setJelszo($adat);
    }

    public function checkJelszo($adat)
    {
        $this->__load();
        return parent::checkJelszo($adat);
    }

    public function getUtolsoklikk()
    {
        $this->__load();
        return parent::getUtolsoklikk();
    }

    public function setUtolsoklikk()
    {
        $this->__load();
        return parent::setUtolsoklikk();
    }

    public function getVendeg()
    {
        $this->__load();
        return parent::getVendeg();
    }

    public function setVendeg($val)
    {
        $this->__load();
        return parent::setVendeg($val);
    }

    public function getIp()
    {
        $this->__load();
        return parent::getIp();
    }

    public function setIp($val)
    {
        $this->__load();
        return parent::setIp($val);
    }

    public function getReferrer()
    {
        $this->__load();
        return parent::getReferrer();
    }

    public function setReferrer($val)
    {
        $this->__load();
        return parent::setReferrer($val);
    }

    public function getSzallito()
    {
        $this->__load();
        return parent::getSzallito();
    }

    public function setSzallito($val)
    {
        $this->__load();
        return parent::setSzallito($val);
    }

    public function getPasswordreminder()
    {
        $this->__load();
        return parent::getPasswordreminder();
    }

    public function setPasswordreminder()
    {
        $this->__load();
        return parent::setPasswordreminder();
    }

    public function clearPasswordreminder()
    {
        $this->__load();
        return parent::clearPasswordreminder();
    }

    public function getOldloginname()
    {
        $this->__load();
        return parent::getOldloginname();
    }

    public function setOldloginname($name)
    {
        $this->__load();
        return parent::setOldloginname($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'created', 'lastmod', 'idegenkod', 'sessionid', 'jelszo', 'inaktiv', 'nev', 'vezeteknev', 'keresztnev', 'adoszam', 'euadoszam', 'mukengszam', 'jovengszam', 'ostermszam', 'valligszam', 'fvmszam', 'cjszam', 'statszamjel', 'irszam', 'varos', 'utca', 'lirszam', 'lvaros', 'lutca', 'telefon', 'mobil', 'fax', 'email', 'honlap', 'megjegyzes', 'syncid', 'uzletkoto', 'teendok', 'esemenyek', 'cimkek', 'fizmod', 'bizonylatfejek', 'kosarak', 'fizhatido', 'szallnev', 'szallirszam', 'szallvaros', 'szallutca', 'nem', 'szuletesiido', 'akcioshirlevelkell', 'ujdonsaghirlevelkell', 'utolsoklikk', 'termekertesitok', 'vendeg', 'ip', 'referrer', 'szallito', 'passwordreminder', 'oldloginname');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}