<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesValutanemProxy extends \Entities\Valutanem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getNev()
    {
        $this->__load();
        return parent::getNev();
    }

    public function setNev($nev)
    {
        $this->__load();
        return parent::setNev($nev);
    }

    public function getKerekit()
    {
        $this->__load();
        return parent::getKerekit();
    }

    public function setKerekit($kerekit)
    {
        $this->__load();
        return parent::setKerekit($kerekit);
    }

    public function getHivatalos()
    {
        $this->__load();
        return parent::getHivatalos();
    }

    public function setHivatalos($hivatalos)
    {
        $this->__load();
        return parent::setHivatalos($hivatalos);
    }

    public function getMincimlet()
    {
        $this->__load();
        return parent::getMincimlet();
    }

    public function setMincimlet($mincimlet)
    {
        $this->__load();
        return parent::setMincimlet($mincimlet);
    }

    public function getBankszamla()
    {
        $this->__load();
        return parent::getBankszamla();
    }

    public function getBankszamlaId()
    {
        $this->__load();
        return parent::getBankszamlaId();
    }

    public function setBankszamla($bankszamla)
    {
        $this->__load();
        return parent::setBankszamla($bankszamla);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nev', 'kerekit', 'hivatalos', 'mincimlet', 'bankszamla', 'bizonylatfejek', 'bizonylattetelek', 'kosarak');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}