$(document).ready(function(){
	$('#mattable-select').mattable({
		addVisible:false,
		filter:{
			fields:['#nevfilter']
		},
		tablebody:{
			url:'/admin/kosar/getlistbody'
		},
		karb:{
			container:'#mattkarb',
			viewUrl:'/admin/kosar/getkarb',
			newWindowUrl:'/admin/kosar/viewkarb',
			saveUrl:'/admin/kosar/save'
		}
	});
	$('#maincheckbox').change(function(){
		$('.egyedcheckbox').attr('checked',$(this).attr('checked'));
	});
});