var mkwmsg = {
	TermekErtesitoKoszonjuk: 'Thank you for your subscription!<br>We will inform you inmediately when the product will be available.',
	TermekErtesitoLeiratkozas: 'Your subscription is ended.',
	TermekKosarba: 'This product is in your cart...',
	TermekValtozatotValassz: 'Please choose the color and size!',
	KosarMennyisegModositas: 'We have modified quantity.',
	KosarMennyisegNulla: 'Please remove this product from your cart with <b>Del</b> button!',
	ChkRegLogin: 'Please choose if you want to register or log in!',
	ChkASZF: 'Please agree with the terms of agreement.',
	ChkKosarValtozott: 'Your cart has changed, please check.',
	ChkKosarUres: 'Your cart is empty.',
    ChkHiba: 'Please fill out missing data.',
    ChkSzallmodHiba: 'Please choose your preferred delivery method.',
    ChkSave: 'Saving your order. Please wait.',
	FiokAdataitModositjuk: 'Saving changes...',
	DialogFejlec: 'Information',
	DialogOk: 'OK',
    PassChange: ['Password change is ready.', 'The two passwords are not the same.', 'Wrong password.','You did not give new password.'],
    PassReminderCreated: 'We have sent a link to your email.',
    PassReminderRequiredEmail: 'Please give us your email address.'
};
var mkwmsghun = {
    TermekErtesitoKoszonjuk: 'Köszönjük feliratkozását!<br>Azonnal értesíteni fogjuk, amint a termék kapható lesz.',
    TermekErtesitoLeiratkozas: 'A leiratkozás folyamatban van.',
    TermekKosarba: 'A terméket a kosarába tettük...',
    TermekValtozatotValassz: 'Válassza ki a lenyíló listából, hogy pontosan milyen termékváltozatot szeretne!',
    KosarMennyisegModositas: 'Módosítottuk a mennyiséget.',
    KosarMennyisegNulla: 'Ha nem kíván vásárolni a termékből, a <b>"Töröl"</b> gombbal veheti ki a kosárból.',
    ChkRegLogin: 'Válassza ki, hogy szeretne-e regisztrálni a vásárláshoz, vagy jelentkezzen be, ha már van nálunk fiókja.',
    ChkASZF: 'Megrendelés előtt kérjük, fogadja el az <b>ÁSZF</b>-et.<br>Ehhez kattintson az <b>"Elolvastam és elfogadom az ÁSZF-et"</b> sor előtti négyzetre.',
    ChkKosarValtozott: 'A kosár tartalma időközben megváltozott, kérem ellenőrizze.',
    ChkKosarUres: 'Az Ön kosara üres.',
    ChkHiba: 'Kérjük, adja meg a hiányzó adatokat. Ezeket pirossal megjelöltük.',
    ChkSzallmodHiba: 'Kérjük adja meg a kívánt szállítási módot.',
    ChkSave: 'Megrendelésének mentése folyamatban. Kérem várjon.',
    FiokAdataitModositjuk: 'Adatait módosítjuk...',
    DialogFejlec: 'Értesítés',
    DialogOk: 'OK',
    PassChange: ['A jelszómódosítás sikerült.', 'A két jelszó nem egyezik.', 'Hibás jelszót adott meg.','Nem adott meg új jelszót.'],
    PassReminderCreated: 'Emailcímére elküldtünk egy jelszóemlékeztető linket.',
    PassReminderRequiredEmail: 'Adja meg azt az emailcímet, amellyel regisztrált.'
};