var superzmsg = {
	TermekErtesitoKoszonjuk: 'Köszönjük feliratkozását!<br>Azonnal értesíteni fogjuk, amint a termék kapható lesz.',
	TermekErtesitoLeiratkozas: 'A leiratkozás folyamatban van.',
	TermekKosarba: 'A terméket a kosarába tettük...',
	TermekValtozatotValassz: 'Válassza ki a lenyíló listából, hogy pontosan milyen termékváltozatot szeretne!',
	KosarMennyisegModositas: 'Módosítottuk a mennyiséget.',
	KosarMennyisegNulla: 'Ha nem kíván vásárolni a termékből, a <b>"Töröl"</b> gombbal veheti ki a kosárból.',
	ChkRegLogin: 'Válassza ki, hogy szeretne-e regisztrálni a vásárláshoz, vagy jelentkezzen be, ha már van nálunk fiókja.',
	ChkASZF: 'Megrendelés előtt kérjük, fogadja el az <b>ÁSZF</b>-et.<br>Ehhez kattintson az <b>"Elolvastam és elfogadom az ÁSZF-et"</b> sor előtti négyzetre.',
	ChkKosarValtozott: 'A kosár tartalma időközben megváltozott, kérem ellenőrizze.',
	ChkKosarUres: 'Az Ön kosara üres.',
    ChkHiba: 'Kérjük, adja meg a hiányzó adatokat. Ezeket pirossal megjelöltük.',
    ChkSave: 'Megrendelésének mentése folyamatban. Kérem várjon.',
	FiokAdataitModositjuk: 'Adatait módosítjuk...',
	DialogFejlec: 'Értesítés',
	DialogOk: 'OK',
    PassChange: ['A jelszómódosítás sikerült.', 'A két jelszó nem egyezik.', 'Hibás jelszót adott meg.','Nem adott meg új jelszót.'],
    PassReminderCreated: 'Emailcímére elküldtünk egy jelszóemlékeztető linket.',
    PassReminderRequiredEmail: 'Adja meg azt az emailcímet, amellyel regisztrált.'
};